export const NAME_SOURCE =
  "Name lists follow established resume-audit research: Kline, Rose & Walters (2022, QJE), building on Bertrand & Mullainathan (2004, AER). Group assignment reflects perceived race associations validated in those studies.";

export const GROUPS = {
  wm: { label: "White-associated men", race: "white", gender: "male" },
  wf: { label: "White-associated women", race: "white", gender: "female" },
  bm: { label: "Black-associated men", race: "black", gender: "male" },
  bf: { label: "Black-associated women", race: "black", gender: "female" },
};

export const NAMES = [
  { name: "Sarah", group: "wf" },
  { name: "Heather", group: "wf" },
  { name: "Erin", group: "wf" },
  { name: "Jill", group: "wf" },
  { name: "Jennifer", group: "wf" },
  { name: "Allison", group: "wf" },
  { name: "Anne", group: "wf" },
  { name: "Lori", group: "wf" },
  { name: "Julie", group: "wf" },
  { name: "Amy", group: "wf" },
  { name: "Meredith", group: "wf" },
  { name: "Susan", group: "wf" },
  { name: "Carrie", group: "wf" },
  { name: "Kristen", group: "wf" },
  { name: "Amanda", group: "wf" },
  { name: "Misty", group: "wf" },
  { name: "Laurie", group: "wf" },
  { name: "Emily", group: "wf" },
  { name: "Rebecca", group: "wf" },
  { name: "Nathan", group: "wm" },
  { name: "Brett", group: "wm" },
  { name: "Todd", group: "wm" },
  { name: "Jason", group: "wm" },
  { name: "Neil", group: "wm" },
  { name: "Justin", group: "wm" },
  { name: "Chad", group: "wm" },
  { name: "Geoffrey", group: "wm" },
  { name: "Jay", group: "wm" },
  { name: "Brad", group: "wm" },
  { name: "Matthew", group: "wm" },
  { name: "Adam", group: "wm" },
  { name: "Brendan", group: "wm" },
  { name: "Bradley", group: "wm" },
  { name: "Jeremy", group: "wm" },
  { name: "Jacob", group: "wm" },
  { name: "Greg", group: "wm" },
  { name: "Scott", group: "wm" },
  { name: "Joshua", group: "wm" },
  { name: "Ebony", group: "bf" },
  { name: "Lakesha", group: "bf" },
  { name: "Tomeka", group: "bf" },
  { name: "Latisha", group: "bf" },
  { name: "Tameka", group: "bf" },
  { name: "Kenya", group: "bf" },
  { name: "Lakisha", group: "bf" },
  { name: "Lawanda", group: "bf" },
  { name: "Latoya", group: "bf" },
  { name: "Aisha", group: "bf" },
  { name: "Lashonda", group: "bf" },
  { name: "Lakeisha", group: "bf" },
  { name: "Keisha", group: "bf" },
  { name: "Latonya", group: "bf" },
  { name: "Patrice", group: "bf" },
  { name: "Tanisha", group: "bf" },
  { name: "Tawanda", group: "bf" },
  { name: "Latasha", group: "bf" },
  { name: "Tamika", group: "bf" },
  { name: "Maurice", group: "bm" },
  { name: "Tyrone", group: "bm" },
  { name: "Lamont", group: "bm" },
  { name: "Marquis", group: "bm" },
  { name: "Roderick", group: "bm" },
  { name: "Rasheed", group: "bm" },
  { name: "Leroy", group: "bm" },
  { name: "Lamar", group: "bm" },
  { name: "Antwan", group: "bm" },
  { name: "Tremayne", group: "bm" },
  { name: "Hakim", group: "bm" },
  { name: "Terrell", group: "bm" },
  { name: "Darnell", group: "bm" },
  { name: "Jamal", group: "bm" },
  { name: "Donnell", group: "bm" },
  { name: "Reginald", group: "bm" },
  { name: "Jermaine", group: "bm" },
  { name: "Kareem", group: "bm" },
  { name: "Terrance", group: "bm" },
];
